Fixed my problem with downloading shorts
AlbertSolomon/tubepy pull request #36
Opened 2023-04-06 18:47 UTC by Sjorza

I added 'or 302' in the file_verification function in lang.py. After I did this, I was able to download this short ("https://www.youtube.com/shorts/FJX5R0PYt8M").

This fixes issue #30

2023-04-07 06:07 UTC, AlbertSolomon requested changes
@Sjorza 👋 This will cause an issue in case where the URL is correct, but the video is not available (or in case where a video was taken down). This is because in this case the function will always return True. Lets try to somehow catch the errors and display them nicely to the user. 🙂

2023-04-07 06:40 UTC, Sjorza commented
That's true, but that only happens with video's that were taken down, right? Or are there any other cases?  I would like to test this and see what happens, but I can't find any examples. Do you have an example?

2023-04-07 07:17 UTC, AlbertSolomon commented
@Sjorza Use ``sample_url`` in lang.py line number 72.

2023-05-15 09:37 UTC, AlbertSolomon reviewed
@Sjorza  Ive provided a hint on how to solve this in ``commit 8f339f0``.  So am closing this PR.

2023-05-15 09:37 UTC, closed without merging